// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameGender = "Gender"

// Gender mapped from table <Gender>
type Gender struct {
	ID        int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	CreatedAt time.Time `gorm:"column:created_at;not null;default:now()" json:"created_at"`
	Name      string    `gorm:"column:Name" json:"Name"`
}

// TableName Gender's table name
func (*Gender) TableName() string {
	return TableNameGender
}
