// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"supabase-to-gorm/model"
)

func newGender(db *gorm.DB, opts ...gen.DOOption) gender {
	_gender := gender{}

	_gender.genderDo.UseDB(db, opts...)
	_gender.genderDo.UseModel(&model.Gender{})

	tableName := _gender.genderDo.TableName()
	_gender.ALL = field.NewAsterisk(tableName)
	_gender.ID = field.NewInt64(tableName, "id")
	_gender.CreatedAt = field.NewTime(tableName, "created_at")
	_gender.Name = field.NewString(tableName, "Name")

	_gender.fillFieldMap()

	return _gender
}

type gender struct {
	genderDo genderDo

	ALL       field.Asterisk
	ID        field.Int64
	CreatedAt field.Time
	Name      field.String

	fieldMap map[string]field.Expr
}

func (g gender) Table(newTableName string) *gender {
	g.genderDo.UseTable(newTableName)
	return g.updateTableName(newTableName)
}

func (g gender) As(alias string) *gender {
	g.genderDo.DO = *(g.genderDo.As(alias).(*gen.DO))
	return g.updateTableName(alias)
}

func (g *gender) updateTableName(table string) *gender {
	g.ALL = field.NewAsterisk(table)
	g.ID = field.NewInt64(table, "id")
	g.CreatedAt = field.NewTime(table, "created_at")
	g.Name = field.NewString(table, "Name")

	g.fillFieldMap()

	return g
}

func (g *gender) WithContext(ctx context.Context) IGenderDo { return g.genderDo.WithContext(ctx) }

func (g gender) TableName() string { return g.genderDo.TableName() }

func (g gender) Alias() string { return g.genderDo.Alias() }

func (g gender) Columns(cols ...field.Expr) gen.Columns { return g.genderDo.Columns(cols...) }

func (g *gender) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := g.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (g *gender) fillFieldMap() {
	g.fieldMap = make(map[string]field.Expr, 3)
	g.fieldMap["id"] = g.ID
	g.fieldMap["created_at"] = g.CreatedAt
	g.fieldMap["Name"] = g.Name
}

func (g gender) clone(db *gorm.DB) gender {
	g.genderDo.ReplaceConnPool(db.Statement.ConnPool)
	return g
}

func (g gender) replaceDB(db *gorm.DB) gender {
	g.genderDo.ReplaceDB(db)
	return g
}

type genderDo struct{ gen.DO }

type IGenderDo interface {
	gen.SubQuery
	Debug() IGenderDo
	WithContext(ctx context.Context) IGenderDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IGenderDo
	WriteDB() IGenderDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IGenderDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IGenderDo
	Not(conds ...gen.Condition) IGenderDo
	Or(conds ...gen.Condition) IGenderDo
	Select(conds ...field.Expr) IGenderDo
	Where(conds ...gen.Condition) IGenderDo
	Order(conds ...field.Expr) IGenderDo
	Distinct(cols ...field.Expr) IGenderDo
	Omit(cols ...field.Expr) IGenderDo
	Join(table schema.Tabler, on ...field.Expr) IGenderDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IGenderDo
	RightJoin(table schema.Tabler, on ...field.Expr) IGenderDo
	Group(cols ...field.Expr) IGenderDo
	Having(conds ...gen.Condition) IGenderDo
	Limit(limit int) IGenderDo
	Offset(offset int) IGenderDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IGenderDo
	Unscoped() IGenderDo
	Create(values ...*model.Gender) error
	CreateInBatches(values []*model.Gender, batchSize int) error
	Save(values ...*model.Gender) error
	First() (*model.Gender, error)
	Take() (*model.Gender, error)
	Last() (*model.Gender, error)
	Find() ([]*model.Gender, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Gender, err error)
	FindInBatches(result *[]*model.Gender, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.Gender) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IGenderDo
	Assign(attrs ...field.AssignExpr) IGenderDo
	Joins(fields ...field.RelationField) IGenderDo
	Preload(fields ...field.RelationField) IGenderDo
	FirstOrInit() (*model.Gender, error)
	FirstOrCreate() (*model.Gender, error)
	FindByPage(offset int, limit int) (result []*model.Gender, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IGenderDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (g genderDo) Debug() IGenderDo {
	return g.withDO(g.DO.Debug())
}

func (g genderDo) WithContext(ctx context.Context) IGenderDo {
	return g.withDO(g.DO.WithContext(ctx))
}

func (g genderDo) ReadDB() IGenderDo {
	return g.Clauses(dbresolver.Read)
}

func (g genderDo) WriteDB() IGenderDo {
	return g.Clauses(dbresolver.Write)
}

func (g genderDo) Session(config *gorm.Session) IGenderDo {
	return g.withDO(g.DO.Session(config))
}

func (g genderDo) Clauses(conds ...clause.Expression) IGenderDo {
	return g.withDO(g.DO.Clauses(conds...))
}

func (g genderDo) Returning(value interface{}, columns ...string) IGenderDo {
	return g.withDO(g.DO.Returning(value, columns...))
}

func (g genderDo) Not(conds ...gen.Condition) IGenderDo {
	return g.withDO(g.DO.Not(conds...))
}

func (g genderDo) Or(conds ...gen.Condition) IGenderDo {
	return g.withDO(g.DO.Or(conds...))
}

func (g genderDo) Select(conds ...field.Expr) IGenderDo {
	return g.withDO(g.DO.Select(conds...))
}

func (g genderDo) Where(conds ...gen.Condition) IGenderDo {
	return g.withDO(g.DO.Where(conds...))
}

func (g genderDo) Order(conds ...field.Expr) IGenderDo {
	return g.withDO(g.DO.Order(conds...))
}

func (g genderDo) Distinct(cols ...field.Expr) IGenderDo {
	return g.withDO(g.DO.Distinct(cols...))
}

func (g genderDo) Omit(cols ...field.Expr) IGenderDo {
	return g.withDO(g.DO.Omit(cols...))
}

func (g genderDo) Join(table schema.Tabler, on ...field.Expr) IGenderDo {
	return g.withDO(g.DO.Join(table, on...))
}

func (g genderDo) LeftJoin(table schema.Tabler, on ...field.Expr) IGenderDo {
	return g.withDO(g.DO.LeftJoin(table, on...))
}

func (g genderDo) RightJoin(table schema.Tabler, on ...field.Expr) IGenderDo {
	return g.withDO(g.DO.RightJoin(table, on...))
}

func (g genderDo) Group(cols ...field.Expr) IGenderDo {
	return g.withDO(g.DO.Group(cols...))
}

func (g genderDo) Having(conds ...gen.Condition) IGenderDo {
	return g.withDO(g.DO.Having(conds...))
}

func (g genderDo) Limit(limit int) IGenderDo {
	return g.withDO(g.DO.Limit(limit))
}

func (g genderDo) Offset(offset int) IGenderDo {
	return g.withDO(g.DO.Offset(offset))
}

func (g genderDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IGenderDo {
	return g.withDO(g.DO.Scopes(funcs...))
}

func (g genderDo) Unscoped() IGenderDo {
	return g.withDO(g.DO.Unscoped())
}

func (g genderDo) Create(values ...*model.Gender) error {
	if len(values) == 0 {
		return nil
	}
	return g.DO.Create(values)
}

func (g genderDo) CreateInBatches(values []*model.Gender, batchSize int) error {
	return g.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (g genderDo) Save(values ...*model.Gender) error {
	if len(values) == 0 {
		return nil
	}
	return g.DO.Save(values)
}

func (g genderDo) First() (*model.Gender, error) {
	if result, err := g.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Gender), nil
	}
}

func (g genderDo) Take() (*model.Gender, error) {
	if result, err := g.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Gender), nil
	}
}

func (g genderDo) Last() (*model.Gender, error) {
	if result, err := g.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Gender), nil
	}
}

func (g genderDo) Find() ([]*model.Gender, error) {
	result, err := g.DO.Find()
	return result.([]*model.Gender), err
}

func (g genderDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Gender, err error) {
	buf := make([]*model.Gender, 0, batchSize)
	err = g.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (g genderDo) FindInBatches(result *[]*model.Gender, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return g.DO.FindInBatches(result, batchSize, fc)
}

func (g genderDo) Attrs(attrs ...field.AssignExpr) IGenderDo {
	return g.withDO(g.DO.Attrs(attrs...))
}

func (g genderDo) Assign(attrs ...field.AssignExpr) IGenderDo {
	return g.withDO(g.DO.Assign(attrs...))
}

func (g genderDo) Joins(fields ...field.RelationField) IGenderDo {
	for _, _f := range fields {
		g = *g.withDO(g.DO.Joins(_f))
	}
	return &g
}

func (g genderDo) Preload(fields ...field.RelationField) IGenderDo {
	for _, _f := range fields {
		g = *g.withDO(g.DO.Preload(_f))
	}
	return &g
}

func (g genderDo) FirstOrInit() (*model.Gender, error) {
	if result, err := g.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Gender), nil
	}
}

func (g genderDo) FirstOrCreate() (*model.Gender, error) {
	if result, err := g.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Gender), nil
	}
}

func (g genderDo) FindByPage(offset int, limit int) (result []*model.Gender, count int64, err error) {
	result, err = g.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = g.Offset(-1).Limit(-1).Count()
	return
}

func (g genderDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = g.Count()
	if err != nil {
		return
	}

	err = g.Offset(offset).Limit(limit).Scan(result)
	return
}

func (g genderDo) Scan(result interface{}) (err error) {
	return g.DO.Scan(result)
}

func (g genderDo) Delete(models ...*model.Gender) (result gen.ResultInfo, err error) {
	return g.DO.Delete(models)
}

func (g *genderDo) withDO(do gen.Dao) *genderDo {
	g.DO = *do.(*gen.DO)
	return g
}
